resources:
  - name: concourse_example
    type: git
    icon: github
    source:
      uri: https://github.com/Xu-Yang-NC/Concourse_Example.git
      branch: main
jobs:
  - name: run-example-job
    plan:
      - get: concourse_example
        trigger: true
      - load_var: previous_status
        file: ((test_status_file_path))
      - task: run-example-test
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: python
              tag: 3.10.6
          inputs:
            - name: concourse_example
          run:
            path: sh
            args:
              - -cx
              - |
                python3 --version
                cd concourse_example
                pip install --no-cache-dir -r requirement.txt
                cd tests
                pytest
